import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  metadataBase: new URL("https://roaahafez.vercel.app"),

  title: "Roaa Hafez – UI/UX Designer",
  description:
    "Portfolio of Roaa Hafez – An Egyptian UI/UX designer who loves simplicity, creativity, and user–centered design.",

  keywords: [
    "Roaa Hafez",
    "Roaa Hafiz",
    "Roa’a Hafez",
    "Roaa UI UX",
    "UI UX Designer Egypt",
    "UI UX Portfolio",
    "UX Research",
    "User Experience Designer",
    "User Interface Designer",
    "Graphic Designer Egypt",
    "Product Designer Egypt",
    "Roaa Design",
    "Creative Designer Egypt",
    "Egyptian Designers",
    "تصميم تجربة المستخدم",
    "مصممة واجهات",
    "رواء حافظ",
    "مصممة مصرية"
  ],

  authors: [{ name: "Roaa Hafez" }],
  creator: "Yahia Elbanna",
  publisher: "Yahia Elbanna",

  themeColor: "#c7a178",

  openGraph: {
    title: "Roaa Hafez – UI/UX Designer",
    description:
      "Explore the work, projects, and creative journey of Roaa Hafez, a UI/UX designer passionate about simplicity and user-centered design.",
    url: "https://roaahafez.vercel.app",
    type: "website",
    images: [
      {
        url: "/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Roaa Hafez Portfolio Preview",
      },
    ],
  },

  twitter: {
    card: "summary_large_image",
    title: "Roaa Hafez – UI/UX Designer",
    description:
      "Portfolio of Roaa Hafez showcasing projects, creativity, and design philosophy.",
    images: ["/og-image.jpg"],
  },

};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
